//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrentonTestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hour
    {
        public int id { get; set; }
        public int hours { get; set; }
        public System.DateTime date { get; set; }
        public int user_id { get; set; }
        public int project_id { get; set; }
        public int status_id { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual status status { get; set; }
        public virtual User User { get; set; }
    }
}
