//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrentonTestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Group
    {
        public int id { get; set; }
        public int project_group1 { get; set; }
        public int user_group { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
